# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ROM_fc/ROM_fc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_fc || ORIG_REF_NAME==ROM_fc} -quiet] -quiet

# IP: ip/ROM_conv2/ROM_conv2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_conv2 || ORIG_REF_NAME==ROM_conv2} -quiet] -quiet

# IP: ip/ROM_conv1/ROM_conv1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_conv1 || ORIG_REF_NAME==ROM_conv1} -quiet] -quiet

# XDC: c:/Users/21047/code/curry_code_summay/rtl_works/BNN_on_fpga/vivado_workspace/vivado_workspace.gen/sources_1/ip/ROM_fc/ROM_fc_ooc.xdc

# XDC: c:/Users/21047/code/curry_code_summay/rtl_works/BNN_on_fpga/vivado_workspace/vivado_workspace.gen/sources_1/ip/ROM_conv2/ROM_conv2_ooc.xdc

# XDC: c:/Users/21047/code/curry_code_summay/rtl_works/BNN_on_fpga/vivado_workspace/vivado_workspace.gen/sources_1/ip/ROM_conv1/ROM_conv1_ooc.xdc
